[phases.setup]
    aptPkgs = [ "git" ,"libboost-all-dev" ,"cmake"]

[phases.git]
    cmds = ["git clone https://github.com/reo7sp/tgbot-cpp"]
    dependsOn = ["setup"]

[phases.cd]
    cmds = ["cd tgbot-cpp"]
    dependsOn = ["git"]

[phases.cmake]
    cmds = ["cmake .","make j4","ls","mv libTgBot.a","cd ..","ls"]
    dependsOn = ["cd"]

[phases.build]
    cmds = ["cmake ."]
    dependsOn = ["cmake"]

[start]
    cmd = "./echobot"
    dependsOn = ["build"]
