[phases.setup]
    aptPkgs = ["g++","make","binutils","cmake","libboost-system-dev","libssl-dev","zlib1g-dev","libcurl4-openssl-dev"]

[phases.git]
    cmds = ["git clone https://github.com/reo7sp/tgbot-cpp"]
    dependsOn = ["setup"]

[phases.tgbot]
    cmds = ["cd tgbot-cpp;cmake .;ls;make -j4;ls;mv libTgBot.a .."]
    dependsOn = ["git"]

[phases.build]
    cmds = ["cmake .","ls","make","ls"]
    dependsOn = ["tgbot"]

[start]
    cmd = "./echobot"
    dependsOn = ["build"]
