[phases.setup]
    aptPkgs = ["g++","make","binutils","cmake","libboost-system-dev","libssl-dev","zlib1g-dev","libcurl4-openssl-dev"]

[phases.git]
    cmds = ["git clone https://github.com/reo7sp/tgbot-cpp"]
    dependsOn = ["setup"]

[phases.cd]
    cmds = ["cd tgbot-cpp"]
    dependsOn = ["git"]

[phases.cmake]
    cmds = ["cmake .","make -j4","ls","mv libTgBot.a","cd ..","ls"]
    dependsOn = ["cd"]

[phases.build]
    cmds = ["cmake ."]
    dependsOn = ["cmake"]

[start]
    cmd = "./echobot"
    dependsOn = ["build"]
