[phases.setup]
    aptPkgs = [ "git"] # Install the ffmpeg package from Nix
    aptPkgs = ["libboost-all-dev"]   # Install the 
    aptPkgs = ["cmake"]

[phases.git]
    cmds = ["git clone https://github.com/reo7sp/tgbot-cpp"]
    dependsOn = ["setup"]

[phases.cd]
    cmds = ["cd tgbot-cpp"]
    dependsOn = ["git"]

[phases.cmake]
    cmds = ["cmake .","make j4","ls","mv libTgBot.a","cd ..","ls"]
    dependsOn = ["cd"]

[phases.build]
    cmds = ["cmake ."]
    dependsOn = ["cmake"]

[phases.clean]
    cmds = ["rm -rf tgbot"]
    dependsOn = ["build"]

[start]
    cmd = "./echobot"
    dependsOn = ["clean"]
